### ISSUE TITLE
validator giving TypeError: Converting circular structure to JSON when running on YAML.

### ISSUE THREAD

**Issue by orientor** [codekie/openapi-examples-validator#67]
I am trying to run openapi-examples-validator on a valid openapi3 YAML file which has been validated by Swagger Editor. My node version is 12.6.1.

I ran the command:
`openapi-examples-validator validated_file.yaml`
I am getting the following error:
```
Validating examples
Schemas with examples found: undefined
Examples without schema found: undefined
Total examples found: undefined

Errors found.

(node:1869) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'FlowCollection'
    |     property 'error' -> object with constructor 'YAMLSemanticError'
    --- property 'source' closes the circle
    at JSON.stringify (<anonymous>)
    at m (/usr/local/share/.config/yarn/global/node_modules/openapi-examples-validator/dist/cli.js:2:3619)
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/openapi-examples-validator/dist/cli.js:2:3106)
    at Generator.next (<anonymous>)
    at r (/usr/local/share/.config/yarn/global/node_modules/openapi-examples-validator/dist/cli.js:2:2392)
    at s (/usr/local/share/.config/yarn/global/node_modules/openapi-examples-validator/dist/cli.js:2:2595)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Any help would be appreciated.

**Comment by codekie** [comment]
Can you please provide me a minimal example to reproduce this error?

**Comment by orientor** [comment]
Yes I finally found the erronous path. I have removed all refs and changed the schema to a simple object yet it is still giving the error. I think there is some problem with the example, hence I have not changed the example much.
```
openapi: 3.0.1
info:
  version: 1.0.0
  title: ab
  description: abc
servers:
- url: 'http://localhost:9991/api/v1'
#######################
# Endpoint definitions
#######################
paths:
  /users:
    get:
      operationId: something
      tags: ["something"]
      description: abcd
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                    - success
                  msg:
                    type: string
              example:
                    {
                       "msg": "",
                       "result": "success",
                       "user": {
                             "date_joined": "2019-10-20T07:50:53.729659+00:00",
                             "full_name": "King Hamlet",
                             "is_guest": false,
                             "profile_data": {
                                "4": {
                                   "value": "vim"
                                },
                                "2": {
                                   "value": "I am:\n* The prince of Denmark\n* Nephew to the usurping Claudius",
                                   "rendered_value": "<p>I am:</p>\n<ul>\n<li>The prince of Denmark</li>\n<li>Nephew to the usurping Claudius</li>\n</ul>"
                                },
                                "5": {
                                   "value": "1900-1-1"
                                },
                                "7": {
                                   "value": "[11]"
                                },
                                "6": {
                                   "value": "YO"
                                },
                                "1": {
                                   "value": "+0-11-23-456-7890",
                                   "rendered_value": "<p>+0-11-23-456-7890</p>"
                                },
                                "8": {
                                   "value": "YO"
                                },
                                "3": {
                                   "rendered_value": "<p>Dark chocolate</p>",
                                   "value": "Dark chocolate"
                                }
                             },
                             "user_id": 10,
                             "is_bot": false,
                             "bot_type": null,
                             "timezone": "",
                             "is_admin": false,
                             "avatar_url": "YO",
                             "is_active": true,
                             "email": "YO"
                          }


                    }

```

**Comment by orientor** [comment]
I found the error. It is because of the extra empty lines just before the final closing brace. Removing them makes it work like normal.

**Comment by codekie** [comment]
I just had a closer look at it. The error is caused by the 3rd-party library https://www.npmjs.com/package/yaml so there is not much I can do about this. The only thing I can do is, to properly pass the original error message of the YAML-parser (wich won't help very much in this particualar case, though: "Insufficient indentation in flow collection")

The logged follow-up error "Converting circular structure to JSON" results from `yaml` passing an error-object with circular references and thus it can't be serialized.

**Comment by codekie** [comment]
If you want this kind of issue to be addressed, please create a new issue in https://github.com/eemeli/yaml . Other than that, #68 is the issue that will handle the error message.

**Comment by orientor** [comment]
Ok, anyway thanks a lot for such a great project!

**Comment by codekie** [comment]
Thanks, for your kind words :)
