### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by thim81** [codekie/openapi-examples-validator#79]
I have a big OpenApi spec with examples, which has references in the spec to the components, which are also in the spec.

OpenApi Extract
```
"paths": {
    "/lists": {
      "get": {
        "summary": "Retrieve list configurations",
        "tags": [
          "Lists"
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/listsResults"
                },
                "examples": {
                  "sample-lists": {
                    "value": {
                      "value": [
                        {
                          "id": 12345,
                          "tenant": "12345-6789-3333-1111-2222",
                          "name": "Master Contact list",
                          "apiName": "master_contact",
                          "systemFields": {
                            "mobile": "MASTER.MOBILE",
                            "language": "MASTER.LANGUAGE"
                          },
                          "type": 1,
                          "requireSegment": true,
                          "created": "2020-01-31T10:31:21",
                          "brands": [
                            {
                              "brandName": "Example",
                              "brandId": "12345-6789-5555-6666-7777"
                            }
                          ]
                        }
                      ],
                      "@count": 68,
                    }
                  }
                }
              }
            }
          },
        },
        "operationId": "get-lists",
        "description": "Returns a list of all list configurations, for all list types.\nThe configurations are returned sorted by name."
      },
      "parameters": []
    },
```

Extract of JSON schema components (in the same spec)

```
    "schemas": {
      "listsResultData": {
        "description": "List configuration query result data.",
        "type": "object",
        "properties": {
          "id": {
            "description": "The unique ID for this list configuration.",
            "type": "integer",
            "format": "int64",
            "example": 12345
          },
          "tenant": {
            "type": "string",
            "description": "The unique ID for the tenant.",
            "format": "uuid",
            "example": "12345-6789-3333-1111-2222"
          },
          "name": {
            "description": "The name of this list.",
            "type": "string"
          },
          "apiName": {
            "description": "The unique API reference for this list configuration.",
            "type": "string",
            "example": "Master list"
          },
          "type": {
            "$ref": "#/components/schemas/listType"
          },
          "systemFields": {
            "description": "Specific system fields for the configuration.",
            "type": "object",
            "properties": {
              "mobile": {
                "type": "string",
                "example": "MASTER.MOBILE"
              },
              "language": {
                "type": "string",
                "example": "MASTER.LANGUAGE"
              },
              "additionalProperties": {
                "type": "object"
              }
            }
          },
          "created": {
            "description": "Creation timestamp of the list configuration",
            "type": "string",
            "format": "date-time",
            "example": "2018-04-25T13:10:23"
          },
          "modified": {
            "description": "Last modified timestamp of the list configuration",
            "type": "string",
            "format": "date-time"
          },
          "description": {
            "type": "string",
            "description": "A descriptive explanation for the created list"
          },
          "requireSegment": {
            "type": "boolean",
            "description": "(TODO)",
            "example": false
          },
          "@count": {
            "description": "Count of the total items",
            "type": "integer",
            "format": "int64"
          }
        },
        "required": [
          "name",
          "apiName",
          "type"
        ]
      },

      "listsResults": {
        "description": "An list configuration result.",
        "type": "object",
        "properties": {
          "value": {
            "description": "Result of the list configurations, based on the query options.",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/listsResultData"
            }
          }
        }
      },
```

When running: 

`openapi validate ./spec/smc-rest-v2.openapi.yaml`

I get the following error:
```
Validating examples
(node:9357) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at JSONPath._trace (/api-reference/node_modules/jsonpath-plus/dist/index-umd.js:643:40)
    at JSONPath._trace (/api-reference/node_modules/jsonpath-plus/dist/index-umd.js:698:19)
    at /api-reference/node_modules/jsonpath-plus/dist/index-umd.js:706:23
    at /api-reference/node_modules/jsonpath-plus/dist/index-umd.js:909:9
    at Array.forEach (<anonymous>)
    at JSONPath._walk (/api-reference/node_modules/jsonpath-plus/dist/index-umd.js:908:24)
    at JSONPath._trace (/api-reference/node_modules/jsonpath-plus/dist/index-umd.js:700:12)
    at /api-reference/node_modules/jsonpath-plus/dist/index-umd.js:706:23
    at /api-reference/node_modules/jsonpath-plus/dist/index-umd.js:909:9
    at Array.forEach (<anonymous>)
```

**Comment by codekie** [comment]
@thim81 Can you please provide a minimal full example? In the provided example, the definition for `#/components/schemas/listType` is missing.

This error message hints to a circular reference.

**Comment by thim81** [comment]
@codekie 

You were right. I had a circular reference. After you tip, I used a more strict Spec validator (https://github.com/IBM/openapi-validator) to correct all specification issues. 
I found a number of issues with the spec, so I sorted that out.

Afterwards I was able to validate the examples, just fine.

Your package is really useful and handy.

**Comment by codekie** [comment]
Thank you :)
